version: "3.9"

services:
  # MongoDB Database (single instance, simple)
  mongodb:
    image: mongo:5.0
    container_name: traffic-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=traffic_db
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - traffic-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Backend API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=traffic_db
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=True
    volumes:
      - ./models:/app/models
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - traffic-network
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

volumes:
  mongo_data:

networks:
  traffic-network:
    driver: bridge
